🔀 :: (entry-77) 접수 현황 집계점수 api 개발
EntryDSM/Equus-Application pull request #60
Opened 2024-06-29 16:43 UTC by rudeh2926

<img width="615" alt="스크린샷 2024-06-30 오전 1 41 22" src="https://github.com/EntryDSM/Equus-Application/assets/125863754/04182aa6-0ed2-440f-889a-c4fc686332a3">

2024-06-30 09:21 UTC, lilseongwon requested changes

2024-06-30 09:21 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
? 걍 ApplicationScore로 해야지 왜 규칙 다 망가뜨림?
조회하는 도메인(같은 도메인일시 생략) + Query/Command + 도메인명

2024-06-30 09:36 UTC, lilseongwon requested changes

2024-06-30 09:36 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/QueryStaticsScoreUseCase.kt
> +                        response.addScore(score!!.totalScore!!.toDouble())
이거 toDouble 타입 맞음? BigDecimal 아니고?

2024-06-30 09:36 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/QueryStaticsScoreUseCase.kt
> +                        response.addScore(score!!.totalScore!!.toDouble())
그리고 저번에 말한거긴 한데 isDaejeon 말고 LivingLocationType에서 Deajeon, ETC등으로 나누고 걍 LivingLocationType.values().map {...} 이런식으로 하는게 낫지 않을까 싶음.
true/false로 나눌거면 if else 쓰는게 낫지 굳이 어렵게 람다식을 써야 하나? 라는 생각이 듦음 (비슷한 PR 전에 봤던거 알고서 하는 얘기)

2024-06-30 09:36 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
매직넘버 쓰지 말라고 했자너. FirstRating SecondRaating 이런식으로 네이밍 다시하셈. companion Object로 만들던가 하고
이런 계산식은 애초에 Domain Service에서 만들라고 말했는디;;

2024-06-30 09:36 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
DTO에서 만들면 도메인 로직이 뿔뿔이 흩어져요

2024-06-30 09:37 UTC, HyunSu1768 commented
이 부분에서 저번에 선생님께서 점수를 나눈 기준이 어떤 기준으로 나눴는지 파악이 되지 않았다고 하셨고, 추후에 명확한 기준과 요구사항을 파악하여 기준이 변경될 수 있다는점 알려드립니다!

2024-06-30 09:38 UTC, HyunSu1768 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
선배 혹시 slack 확인 가능하실까요!

2024-06-30 09:45 UTC, lilseongwon requested changes

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +    ): List<Score?> {
이거 null이면 알아서 EmptyList 반환해주지 않음?

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +            .map { scoreMapper.toDomain(it) ?: throw ScoreExceptions.ScoreNotFoundException() }
왜 infra 모듈에서 DomainException을 사용하는거임?

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +            )
걍 이너조인을 하는게 낫지 않나.. mysql 엔진이 알아서 서브쿼리를 조인으로 바꿔주는 경우도 있다고는 하는데...
성능차이 테스트 함 해보는게;
뭐 근데 시간 없으면 이건 일단 패스. 
https://jojoldu.tistory.com/520
시간날때 봐봐. 지금보지 말고

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
>          return jpaQueryFactory.select(scoreJpaEntity.totalScore)
이것도 말은 안했지만 이런거 최대한 자제. 조회성능 차이 얼마 안나면 최대한 변경에 유연하게 구현사항은 메서드명으로 안꺼내는게 좋음

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/WebScoreAdapter.kt
>  }
그냥 총점수 조회할때 Response 필드를 nullable로 하는게 어떤지...
기본적으로 아무것도 반환이 안되면 클라이언트는 당황할 확률이 높음

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/WebScoreAdapter.kt
>  }
이건 무조건 바꾸셈

2024-06-30 09:45 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
이게 어제 말한 json property 같은데 걍 필드명 바꾸명 해결되니까 삭제 ㄱ

2024-06-30 09:45 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
지금 할게요

2024-06-30 09:47 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +    ): List<Score?> {
몰라서 그러니까 확인하고 커밋 ㄱ

2024-06-30 10:01 UTC, HyunSu1768 commented
> 이 부분에서 저번에 선생님께서 점수를 나눈 기준이 어떤 기준으로 나눴는지 파악이 되지 않았다고 하셨고, 추후에 명확한 기준과 요구사항을 파악하여 기준이 변경될 수 있다는점 알려드립니다!

따라서 이번 pr 에서 딱 정해져 있는 score 기준이 아닌, 유연하게 변경되어도 결과가 잘 나올 수 있는 로직을 설계하면 좋을것 같습니다.

2024-06-30 10:02 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
변경될 수 있다는 점 숙지하고 얘기하자면 
왜 Score에서도 계산하는 로직이 있는데 도메인 서비스에서 해야 하나? 라는 궁금증이 들 수도 있을거 같아 tmi를 써볼게요.
일단 최대한 도메인 모델 안에 로직을 모아놓는게 좋겠지만, '저 Score 모델이 자기가 몇번째 점수 유형 으로 분류되는지 알 책임이 있을까?' 처럼 자신이 아는 정보가 아닐 때 계산을 하는 로직은 도메인 서비스에 넣는게 좋지 않나 라고 생각함.

2024-06-30 10:28 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
넵

2024-06-30 10:31 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +            )
넵

2024-06-30 10:32 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
넵

2024-06-30 10:33 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
필드명을 그냥 숫자로 변경하면 오류가 나는걸로 알고있습니다

2024-06-30 10:35 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
? 필드명이 FirstRate, SecondRate 이런식으로 하면 되니까 JsonProperty 필요없고 이 Response도 삭제하면 되는거 아님?

2024-06-30 10:35 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/WebScoreAdapter.kt
>  }
[48f64ee](https://github.com/EntryDSM/Equus-Application/pull/60/commits/48f64eebef29a062555204281a046ec9c81a3793)

2024-06-30 10:35 UTC, lilseongwon commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
rollsroyce에서 저렇게 했는지는 모르지만 만약 그랬다면 바꿔야 한다고 생각함.

2024-06-30 10:36 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/QueryStaticsScoreUseCase.kt
> +                        response.addScore(score!!.totalScore!!.toDouble())
아니면 map써서 score.totalScore만 list로 빼오는것도...

2024-06-30 10:38 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/WebScoreAdapter.kt
>  }
[6da7cb1](https://github.com/EntryDSM/Equus-Application/pull/60/commits/6da7cb1fd9694d16d2fb136ec0de40921e63b586)

2024-06-30 10:41 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +            .map { scoreMapper.toDomain(it) ?: throw ScoreExceptions.ScoreNotFoundException() }
[6b7a4d3](https://github.com/EntryDSM/Equus-Application/pull/60/commits/6b7a4d3c4de3904894a7963679f511687c0c2777)

2024-06-30 10:42 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
>          return jpaQueryFactory.select(scoreJpaEntity.totalScore)
넵

2024-06-30 11:15 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/QueryStaticsScoreUseCase.kt
> +                        response.addScore(score!!.totalScore!!.toDouble())
[e21a49b](https://github.com/EntryDSM/Equus-Application/pull/60/commits/e21a49b522851fb43084867daba1f18532b8b0fb)
[429e19f](https://github.com/EntryDSM/Equus-Application/pull/60/commits/429e19f6447f1bc4018a178f3a4a6447839b78bf)

2024-06-30 11:15 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/presentation/dto/reponse/GetScoreResponse.kt
> +    @JsonProperty("-79") val score_79: Int = 0
[429e19f](https://github.com/EntryDSM/Equus-Application/pull/60/commits/429e19f6447f1bc4018a178f3a4a6447839b78bf)
[02cbbc8](https://github.com/EntryDSM/Equus-Application/pull/60/commits/02cbbc851e8ac41e5708fc1d28c88b55d752f238)

2024-06-30 11:16 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +    ): List<Score?> {
[10d2479](https://github.com/EntryDSM/Equus-Application/pull/60/commits/10d2479125aaf1e88b95f99720295851d7abcc78)
반환이 안돼서  .let한다음 emptyList 했습니다

2024-06-30 11:16 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
[9eac930](https://github.com/EntryDSM/Equus-Application/pull/60/commits/9eac930098e5608097ea62d05e6e80f39e0973fc)

2024-06-30 12:36 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/QueryStaticsScoreUseCase.kt
> +                        response.addScore(score!!.totalScore!!.toDouble())
[98530ac](https://github.com/EntryDSM/Equus-Application/pull/60/commits/98530ac816ebaa4c56805659b2df0a5d77e92e02)

2024-06-30 12:37 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
[e28573c](https://github.com/EntryDSM/Equus-Application/pull/60/commits/e28573ce2704f854f7667cc86ee8fbaebc4ec497)

2024-06-30 12:39 UTC, rudeh2926 commented on application-infrastructure/src/main/kotlin/hs/kr/equus/application/domain/score/domain/ScorePersistenceAdapter.kt
> +    ): List<Score?> {
[f76a9d2](https://github.com/EntryDSM/Equus-Application/pull/60/commits/f76a9d27e721a6024d2c010711aa13b106923fd3)

2024-07-01 12:37 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
;;

2024-07-01 12:38 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
조회하는 도메인(같은 도메인일시 생략) + Query/Command + 도메인명

2024-07-01 12:38 UTC, lilseongwon commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/spi/ScorePort.kt
> +        ScoreQueryApplicationTypeAndIsDaejeonPort
걍 기존에 있는 ApplicationQueryScore로 해야죠..

2024-07-02 08:00 UTC, rudeh2926 commented on application-domain/src/main/kotlin/hs/kr/equus/application/domain/score/usecase/dto/response/GetStaticsScoreResponse.kt
> +        }
[027d3c2](https://github.com/EntryDSM/Equus-Application/pull/60/commits/027d3c2a598ef907908476db9df6318fbce1da32)
[ada48a4](https://github.com/EntryDSM/Equus-Application/pull/60/commits/ada48a4302b997282c5f9cdcabff3919dd418279)

2024-07-02 08:20 UTC, lilseongwon approved these changes

2024-07-02 12:49 UTC, merged